# Generated by Django 6.0.4 on 2026-09-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_poster_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='hall',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
