# Generated by Django 6.0.4 on 2026-09-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0006_hall_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=120, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='poster',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=180, null=True, unique=True, verbose_name='URL'),
        ),
    ]
